/*
	FILE ARCHIVED ON 4:47:53 θών 25, 2014 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 18:20:47 ΰοπ 4, 2015.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
$(function(){
	$("img.lazy").lazyload({
		effect : "fadeIn"
	});
});